// Mocks generated by Mockito 5.4.5 from annotations
// in clicktactoe/test/utils/unittest/game/LocalGameStateManagerTest.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cancellation_token/cancellation_token.dart' as _i5;
import 'package:clicktactoe/modules/game/interfaces/domain/GamePoint.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'LocalGameStateManagerTest.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MockPlayerNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockPlayerNotifier extends _i1.Mock
    implements _i2.MockPlayerNotifier {
  MockMockPlayerNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onPointSelected(_i3.GamePoint? point) => super.noSuchMethod(
    Invocation.method(#onPointSelected, [point]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> handleMove(
    List<_i3.GamePoint>? table,
    _i5.CancellationToken? cancellationToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleMove, [table, cancellationToken]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void restart() => super.noSuchMethod(
    Invocation.method(#restart, []),
    returnValueForMissingStub: null,
  );
}
